### ISSUE TITLE
Fazer cadastro Currículo Lattes

### ISSUE THREAD

**Issue by lucileidedantas** [IFRN-SC/The_Zeta_Project#13]
Fazer o currículo na plataforma Lattes.

Segue o link: http://lattes.cnpq.br/ (Abrir menu: Cadastrar novo currículo - Menu lateral à direita).

Precisamos que vocês se cadastrem nessa plataforma para poder cadastrar vocês em projetos no SUAP e até em alguns eventos.

**Comment by Leticiassantos19** [comment]
http://lattes.cnpq.br/7734857407033075

**Comment by Ithaelly** [comment]
http://lattes.cnpq.br/7043620041268227

**Comment by PabloHenriqueO** [comment]
http://lattes.cnpq.br/5446412940147883
