### ISSUE TITLE
Criar função seguir linha 

### ISSUE THREAD

**Issue by Leticiassantos19** [IFRN-SC/The_Zeta_Project#9]

**Comment by lennedy** [comment]
Letícia, esse código foi testado?

**Comment by Leticiassantos19** [comment]
Não, testei e teve alguns erros, desde então vou concertar para enviar novamente testado. 😉

________________________________
De: lennedy <notifications@github.com>
Enviado: sábado, 12 de maio de 2018 16:27:19
Para: IFRN-SC/The_Zeta_Project
Cc: Leticiassantos19; State change
Assunto: Re: [IFRN-SC/The_Zeta_Project] Criar função seguir linha (#9)


Letícia, esse código foi testado?
